// <auto-generated />
using System;
using Example_Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example_Persistance.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20200210113642_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Example_Persistance.Model.AwardArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerAwardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAwardId");

                    b.ToTable("AwardArticles");
                });

            modelBuilder.Entity("Example_Persistance.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Example_Persistance.Model.PlayerArticle", b =>
                {
                    b.Property<int>("PlayerArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StorageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerArticleId");

                    b.HasIndex("StorageId");

                    b.ToTable("PlayerArticles");
                });

            modelBuilder.Entity("Example_Persistance.Model.PlayerAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Collected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAwards");
                });

            modelBuilder.Entity("Example_Persistance.Model.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StorageId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Example_Persistance.Model.AwardArticle", b =>
                {
                    b.HasOne("Example_Persistance.Model.PlayerAward", "PlayerAward")
                        .WithMany("AwardArticles")
                        .HasForeignKey("PlayerAwardId");
                });

            modelBuilder.Entity("Example_Persistance.Model.PlayerArticle", b =>
                {
                    b.HasOne("Example_Persistance.Model.Storage", "Storage")
                        .WithMany("Items")
                        .HasForeignKey("StorageId");
                });

            modelBuilder.Entity("Example_Persistance.Model.PlayerAward", b =>
                {
                    b.HasOne("Example_Persistance.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Example_Persistance.Model.Storage", b =>
                {
                    b.HasOne("Example_Persistance.Model.Player", "Player")
                        .WithOne("Storage")
                        .HasForeignKey("Example_Persistance.Model.Storage", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
